import { AdminLocale } from '../../core/i18n/i18n.service';

export const SETTINGS_TRANSLATIONS: Record<AdminLocale, Record<string, string>> = {
  vi: {
    eyebrow: 'THÔNG TIN DOANH NGHIỆP', title: 'Cài đặt công ty', description: 'Quản lý thông tin pháp lý, thương hiệu, liên hệ và các kênh hiển thị trên website.',
    settings: 'Cấu hình', branches: 'Chi nhánh', hours: 'Giờ làm việc', socialLinks: 'Mạng xã hội', contactChannels: 'Kênh liên hệ', add: 'Thêm mới', edit: 'Sửa', delete: 'Xóa', active: 'Đang hoạt động', inactive: 'Tạm ẩn', primary: 'Chính', headOffice: 'Trụ sở chính', empty: 'Chưa có dữ liệu.', save: 'Lưu thay đổi', saved: 'Đã lưu thay đổi.', deleted: 'Đã xóa dữ liệu.', loadError: 'Không thể tải cài đặt công ty.', operationError: 'Không thể thực hiện thao tác.', confirmDelete: 'Bạn có chắc muốn xóa {name}?', global: 'Toàn công ty', scope: 'Phạm vi áp dụng', day: 'Ngày', opens: 'Mở cửa', closes: 'Đóng cửa', closed: 'Nghỉ', statusEnabled: 'Sử dụng', secretHint: 'Để trống để giữ nguyên. Nhập env:TEN_BIEN hoặc giá trị cần mã hóa.',
    company: 'Công ty', legal: 'Pháp lý', contact: 'Liên hệ', social: 'Mạng xã hội', branding: 'Thương hiệu', business_hours: 'Giờ làm việc', map: 'Bản đồ', quote: 'Báo giá', email: 'Email', seo_defaults: 'SEO mặc định', feature_flags: 'Tính năng',
    company_name: 'Tên công ty', short_name: 'Tên ngắn', default_locale: 'Ngôn ngữ mặc định', legal_name: 'Tên pháp lý', tax_code: 'Mã số thuế', representative: 'Người đại diện', primary_phone: 'Điện thoại chính', primary_email: 'Email chính', primary_address: 'Địa chỉ chính', links_nofollow: 'Gắn nofollow cho liên kết', logo_media_id: 'Media ID logo', favicon_media_id: 'Media ID favicon', default_og_media_id: 'Media ID Open Graph', timezone: 'Múi giờ', display_note: 'Ghi chú hiển thị', embed_url: 'URL nhúng bản đồ', latitude: 'Vĩ độ', longitude: 'Kinh độ', enabled: 'Bật nhận báo giá', recipient_email: 'Email nhận báo giá', auto_reply_enabled: 'Tự động trả lời', from_name: 'Tên người gửi', from_address: 'Email người gửi', smtp_password: 'Mật khẩu SMTP', site_title: 'Tiêu đề website', meta_description: 'Mô tả SEO mặc định', maintenance_banner_enabled: 'Hiển thị thông báo bảo trì', public_contact_forms_enabled: 'Bật form liên hệ công khai',
    sun: 'Chủ nhật', mon: 'Thứ hai', tue: 'Thứ ba', wed: 'Thứ tư', thu: 'Thứ năm', fri: 'Thứ sáu', sat: 'Thứ bảy',
  },
  en: {
    eyebrow: 'COMPANY INFORMATION', title: 'Company settings', description: 'Manage legal, branding, contact, and public channel information.', settings: 'Settings', branches: 'Branches', hours: 'Business hours', socialLinks: 'Social links', contactChannels: 'Contact channels', add: 'Add', edit: 'Edit', delete: 'Delete', active: 'Active', inactive: 'Hidden', primary: 'Primary', headOffice: 'Head office', empty: 'No data yet.', save: 'Save changes', saved: 'Changes saved.', deleted: 'Record deleted.', loadError: 'Unable to load company settings.', operationError: 'Unable to complete the operation.', confirmDelete: 'Delete {name}?', global: 'Company-wide', scope: 'Applies to', day: 'Day', opens: 'Opens', closes: 'Closes', closed: 'Closed', statusEnabled: 'Enabled', secretHint: 'Leave blank to keep the current value. Enter env:VARIABLE or a value to encrypt.',
    company: 'Company', legal: 'Legal', contact: 'Contact', social: 'Social', branding: 'Branding', business_hours: 'Business hours', map: 'Map', quote: 'Quote', email: 'Email', seo_defaults: 'SEO defaults', feature_flags: 'Features', company_name: 'Company name', short_name: 'Short name', default_locale: 'Default language', legal_name: 'Legal name', tax_code: 'Tax code', representative: 'Representative', primary_phone: 'Primary phone', primary_email: 'Primary email', primary_address: 'Primary address', links_nofollow: 'Use nofollow links', logo_media_id: 'Logo media ID', favicon_media_id: 'Favicon media ID', default_og_media_id: 'Open Graph media ID', timezone: 'Timezone', display_note: 'Display note', embed_url: 'Map embed URL', latitude: 'Latitude', longitude: 'Longitude', enabled: 'Enable quote requests', recipient_email: 'Quote recipient email', auto_reply_enabled: 'Automatic reply', from_name: 'Sender name', from_address: 'Sender email', smtp_password: 'SMTP password', site_title: 'Site title', meta_description: 'Default SEO description', maintenance_banner_enabled: 'Maintenance banner', public_contact_forms_enabled: 'Public contact forms', sun: 'Sunday', mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday', thu: 'Thursday', fri: 'Friday', sat: 'Saturday',
  },
  zh: {
    eyebrow: '公司信息', title: '公司设置', description: '管理法律、品牌、联系信息和公开渠道。', settings: '设置', branches: '分支机构', hours: '营业时间', socialLinks: '社交链接', contactChannels: '联系渠道', add: '添加', edit: '编辑', delete: '删除', active: '启用', inactive: '隐藏', primary: '主要', headOffice: '总部', empty: '暂无数据。', save: '保存更改', saved: '更改已保存。', deleted: '记录已删除。', loadError: '无法加载公司设置。', operationError: '无法完成操作。', confirmDelete: '确定删除 {name}？', global: '全公司', scope: '适用范围', day: '星期', opens: '开始', closes: '结束', closed: '休息', statusEnabled: '启用', secretHint: '留空以保留当前值。输入 env:VARIABLE 或需要加密的值。',
    company: '公司', legal: '法律信息', contact: '联系信息', social: '社交设置', branding: '品牌', business_hours: '营业时间', map: '地图', quote: '报价', email: '电子邮件', seo_defaults: '默认 SEO', feature_flags: '功能', company_name: '公司名称', short_name: '简称', default_locale: '默认语言', legal_name: '法定名称', tax_code: '税号', representative: '法定代表人', primary_phone: '主要电话', primary_email: '主要邮箱', primary_address: '主要地址', links_nofollow: '链接使用 nofollow', logo_media_id: 'Logo 媒体 ID', favicon_media_id: 'Favicon 媒体 ID', default_og_media_id: 'Open Graph 媒体 ID', timezone: '时区', display_note: '显示说明', embed_url: '地图嵌入链接', latitude: '纬度', longitude: '经度', enabled: '启用报价请求', recipient_email: '报价接收邮箱', auto_reply_enabled: '自动回复', from_name: '发件人名称', from_address: '发件人邮箱', smtp_password: 'SMTP 密码', site_title: '网站标题', meta_description: '默认 SEO 描述', maintenance_banner_enabled: '维护通知', public_contact_forms_enabled: '公开联系表单', sun: '星期日', mon: '星期一', tue: '星期二', wed: '星期三', thu: '星期四', fri: '星期五', sat: '星期六',
  },
};

export const DIRECTORY_TRANSLATIONS: Record<AdminLocale, Record<string, string>> = {
  vi: { branch: 'chi nhánh', social: 'liên kết mạng xã hội', contact: 'kênh liên hệ', create: 'Thêm', update: 'Cập nhật', name: 'Tên', code: 'Mã', address: 'Địa chỉ', phone: 'Điện thoại', email: 'Email', platform: 'Nền tảng', label: 'Nhãn hiển thị', url: 'URL HTTPS', icon: 'Mã icon', type: 'Loại kênh', value: 'Giá trị', href: 'Liên kết thao tác', note: 'Ghi chú thời gian hỗ trợ', order: 'Thứ tự', active: 'Đang hoạt động', primary: 'Kênh chính', head: 'Trụ sở chính', cancel: 'Hủy', save: 'Lưu' },
  en: { branch: 'branch', social: 'social link', contact: 'contact channel', create: 'Add', update: 'Update', name: 'Name', code: 'Code', address: 'Address', phone: 'Phone', email: 'Email', platform: 'Platform', label: 'Display label', url: 'HTTPS URL', icon: 'Icon key', type: 'Channel type', value: 'Value', href: 'Action link', note: 'Availability note', order: 'Order', active: 'Active', primary: 'Primary channel', head: 'Head office', cancel: 'Cancel', save: 'Save' },
  zh: { branch: '分支机构', social: '社交链接', contact: '联系渠道', create: '添加', update: '更新', name: '名称', code: '代码', address: '地址', phone: '电话', email: '电子邮箱', platform: '平台', label: '显示标签', url: 'HTTPS 链接', icon: '图标代码', type: '渠道类型', value: '值', href: '操作链接', note: '服务时间说明', order: '顺序', active: '启用', primary: '主要渠道', head: '总部', cancel: '取消', save: '保存' },
};
