import { ShowcaseLocale } from './showcase.models';
type Dictionary = Readonly<Record<string, string>>;

export const SHOWCASE_TRANSLATIONS: Readonly<Record<ShowcaseLocale, Dictionary>> = {
  vi: {
    eyebrow: 'NỘI DUNG DOANH NGHIỆP', title: 'Trưng bày & hồ sơ năng lực', subtitle: 'Quản lý bộ sưu tập, đối tác, chứng nhận và dự án bằng ba ngôn ngữ.',
    galleries: 'Bộ sưu tập', galleryItems: 'Media bộ sưu tập', partners: 'Đối tác', certifications: 'Chứng nhận', projects: 'Dự án',
    addGallery: 'Thêm bộ sưu tập', addGalleryItem: 'Thêm media', addPartner: 'Thêm đối tác', addCertification: 'Thêm chứng nhận', addProject: 'Thêm dự án', refresh: 'Làm mới',
    search: 'Tìm kiếm', status: 'Trạng thái', allStatuses: 'Tất cả trạng thái', dataScope: 'Phạm vi dữ liệu', activeOnly: 'Đang sử dụng', trashOnly: 'Thùng rác', apply: 'Áp dụng', clear: 'Xóa lọc',
    empty: 'Chưa có dữ liệu phù hợp.', loadError: 'Không thể tải dữ liệu trưng bày.', operationError: 'Không thể thực hiện thao tác.', publicDeferred: 'Website public và block Page Builder sẽ được kết nối ở giai đoạn frontend cuối cùng; nguồn dữ liệu Backend hiện chỉ trả bản đã xuất bản.',
    create: 'Tạo', editItem: 'Chỉnh sửa', general: 'Thông tin chung', localized: 'Nội dung đa ngôn ngữ', media: 'Media', code: 'Mã', gallery: 'Bộ sưu tập', noSelection: 'Chưa chọn', featured: 'Nổi bật', order: 'Thứ tự', website: 'Website', issuedOn: 'Ngày cấp', expiresOn: 'Ngày hết hạn', startedOn: 'Ngày bắt đầu', completedOn: 'Ngày hoàn thành', documentVisibility: 'Quyền tải tài liệu', private: 'Nội bộ', public: 'Công khai',
    name: 'Tên', titleField: 'Tiêu đề', slug: 'Slug', description: 'Mô tả / tóm tắt', content: 'Nội dung chi tiết', location: 'Địa điểm', issuer: 'Đơn vị cấp', altText: 'Alt text', caption: 'Chú thích', documentLabel: 'Nhãn tải tài liệu', languageVi: 'Tiếng Việt', languageEn: 'Tiếng Anh', languageZh: 'Tiếng Trung',
    chooseMedia: 'Chọn media', chooseLogo: 'Chọn logo', chooseImage: 'Chọn ảnh', chooseDocument: 'Chọn PDF', chooseProjectMedia: 'Chọn media dự án', remove: 'Bỏ chọn', selectedMedia: 'Media đã chọn',
    draft: 'Bản nháp', published: 'Đã xuất bản', archived: 'Đã lưu trữ', save: 'Lưu', cancel: 'Hủy', close: 'Đóng', edit: 'Sửa', delete: 'Xóa', publish: 'Xuất bản', archive: 'Lưu trữ', restore: 'Khôi phục',
    created: 'Đã tạo dữ liệu.', updated: 'Đã cập nhật dữ liệu.', deleted: 'Đã chuyển vào thùng rác.', publishedMessage: 'Đã xuất bản dữ liệu.', archivedMessage: 'Đã lưu trữ dữ liệu.', restoredMessage: 'Đã khôi phục dữ liệu.', confirmDelete: 'Chuyển dữ liệu này vào thùng rác?', mediaRequired: 'Hãy chọn media phù hợp.',
  },
  en: {
    eyebrow: 'COMPANY CONTENT', title: 'Showcase & credentials', subtitle: 'Manage galleries, partners, certifications and projects in three languages.', galleries: 'Galleries', galleryItems: 'Gallery media', partners: 'Partners', certifications: 'Certifications', projects: 'Projects', addGallery: 'Add gallery', addGalleryItem: 'Add media', addPartner: 'Add partner', addCertification: 'Add certification', addProject: 'Add project', refresh: 'Refresh', search: 'Search', status: 'Status', allStatuses: 'All statuses', dataScope: 'Data scope', activeOnly: 'Active items', trashOnly: 'Trash', apply: 'Apply', clear: 'Clear filters', empty: 'No matching data.', loadError: 'Unable to load showcase data.', operationError: 'Unable to complete the operation.', publicDeferred: 'Public pages and Page Builder blocks will be connected in the final frontend phase; the Backend data source already returns published records only.', create: 'Create', editItem: 'Edit', general: 'General', localized: 'Localized content', media: 'Media', code: 'Code', gallery: 'Gallery', noSelection: 'None', featured: 'Featured', order: 'Order', website: 'Website', issuedOn: 'Issued on', expiresOn: 'Expires on', startedOn: 'Started on', completedOn: 'Completed on', documentVisibility: 'Document visibility', private: 'Private', public: 'Public', name: 'Name', titleField: 'Title', slug: 'Slug', description: 'Description / summary', content: 'Detailed content', location: 'Location', issuer: 'Issuer', altText: 'Alt text', caption: 'Caption', documentLabel: 'Download label', languageVi: 'Vietnamese', languageEn: 'English', languageZh: 'Chinese', chooseMedia: 'Choose media', chooseLogo: 'Choose logo', chooseImage: 'Choose image', chooseDocument: 'Choose PDF', chooseProjectMedia: 'Choose project media', remove: 'Remove', selectedMedia: 'Selected media', draft: 'Draft', published: 'Published', archived: 'Archived', save: 'Save', cancel: 'Cancel', close: 'Close', edit: 'Edit', delete: 'Delete', publish: 'Publish', archive: 'Archive', restore: 'Restore', created: 'Data created.', updated: 'Data updated.', deleted: 'Moved to trash.', publishedMessage: 'Data published.', archivedMessage: 'Data archived.', restoredMessage: 'Data restored.', confirmDelete: 'Move this item to trash?', mediaRequired: 'Select appropriate media.',
  },
  zh: {
    eyebrow: '企业内容', title: '展示与资质', subtitle: '使用三种语言管理图库、合作伙伴、认证和项目。', galleries: '图库', galleryItems: '图库媒体', partners: '合作伙伴', certifications: '认证', projects: '项目', addGallery: '添加图库', addGalleryItem: '添加媒体', addPartner: '添加合作伙伴', addCertification: '添加认证', addProject: '添加项目', refresh: '刷新', search: '搜索', status: '状态', allStatuses: '全部状态', dataScope: '数据范围', activeOnly: '使用中', trashOnly: '回收站', apply: '应用', clear: '清除筛选', empty: '没有匹配的数据。', loadError: '无法加载展示数据。', operationError: '无法完成操作。', publicDeferred: '公共页面和 Page Builder 区块将在最后的前端阶段连接；Backend 数据源目前仅返回已发布记录。', create: '创建', editItem: '编辑', general: '基本信息', localized: '多语言内容', media: '媒体', code: '代码', gallery: '图库', noSelection: '未选择', featured: '推荐', order: '顺序', website: '网站', issuedOn: '签发日期', expiresOn: '到期日期', startedOn: '开始日期', completedOn: '完成日期', documentVisibility: '文件可见性', private: '内部', public: '公开', name: '名称', titleField: '标题', slug: 'Slug', description: '描述 / 摘要', content: '详细内容', location: '地点', issuer: '签发机构', altText: '替代文本', caption: '说明', documentLabel: '下载标签', languageVi: '越南语', languageEn: '英语', languageZh: '中文', chooseMedia: '选择媒体', chooseLogo: '选择标志', chooseImage: '选择图片', chooseDocument: '选择 PDF', chooseProjectMedia: '选择项目媒体', remove: '移除', selectedMedia: '已选媒体', draft: '草稿', published: '已发布', archived: '已归档', save: '保存', cancel: '取消', close: '关闭', edit: '编辑', delete: '删除', publish: '发布', archive: '归档', restore: '恢复', created: '数据已创建。', updated: '数据已更新。', deleted: '已移至回收站。', publishedMessage: '数据已发布。', archivedMessage: '数据已归档。', restoredMessage: '数据已恢复。', confirmDelete: '将此项移至回收站？', mediaRequired: '请选择合适的媒体。',
  },
};
