import { AdminLocale } from '../../core/i18n/i18n.service';

const TOKEN_NAMES: Record<AdminLocale, Readonly<Record<string, string>>> = {
  vi: { brand: 'Màu thương hiệu', brand_strong: 'Thương hiệu đậm', brand_deep: 'Thương hiệu sâu', brand_soft: 'Nền thương hiệu nhạt', accent: 'Màu nhấn', surface: 'Nền chính', surface_muted: 'Nền phụ', surface_dark: 'Nền tối', text: 'Chữ chính', text_muted: 'Chữ phụ', border: 'Đường viền', focus: 'Viền focus', body: 'Font nội dung', heading: 'Font tiêu đề', base: 'Cỡ chữ cơ sở', small: 'Nhỏ', large: 'Lớn', h1_min: 'H1 nhỏ nhất', h1_max: 'H1 lớn nhất', h2_min: 'H2 nhỏ nhất', h2_max: 'H2 lớn nhất', xs: 'Khoảng XS', sm: 'Khoảng S', md: 'Khoảng M', lg: 'Khoảng L', xl: 'Khoảng XL', '2xl': 'Khoảng 2XL', '3xl': 'Khoảng 3XL', preset: 'Kiểu có sẵn', max: 'Chiều rộng tối đa', narrow: 'Khung hẹp', gutter_min: 'Lề nhỏ nhất', gutter_max: 'Lề lớn nhất', min_height: 'Chiều cao tối thiểu', horizontal_padding: 'Đệm ngang', radius: 'Bo góc nút', font_weight: 'Độ đậm chữ', line_height: 'Chiều cao dòng', gap: 'Khoảng cách section' },
  en: { brand: 'Brand color', brand_strong: 'Strong brand', brand_deep: 'Deep brand', brand_soft: 'Soft brand surface', accent: 'Accent color', surface: 'Main surface', surface_muted: 'Muted surface', surface_dark: 'Dark surface', text: 'Primary text', text_muted: 'Muted text', border: 'Border', focus: 'Focus ring', body: 'Body font', heading: 'Heading font', base: 'Base font size', small: 'Small', large: 'Large', h1_min: 'Minimum H1', h1_max: 'Maximum H1', h2_min: 'Minimum H2', h2_max: 'Maximum H2', xs: 'XS spacing', sm: 'S spacing', md: 'M spacing', lg: 'L spacing', xl: 'XL spacing', '2xl': '2XL spacing', '3xl': '3XL spacing', preset: 'Preset', max: 'Maximum width', narrow: 'Narrow width', gutter_min: 'Minimum gutter', gutter_max: 'Maximum gutter', min_height: 'Minimum height', horizontal_padding: 'Horizontal padding', radius: 'Button radius', font_weight: 'Font weight', line_height: 'Line height', gap: 'Section gap' },
  zh: { brand: '品牌颜色', brand_strong: '深品牌色', brand_deep: '最深品牌色', brand_soft: '浅品牌背景', accent: '强调色', surface: '主背景', surface_muted: '次背景', surface_dark: '深色背景', text: '主文字', text_muted: '次文字', border: '边框', focus: '焦点边框', body: '正文字体', heading: '标题字体', base: '基础字号', small: '小', large: '大', h1_min: 'H1 最小值', h1_max: 'H1 最大值', h2_min: 'H2 最小值', h2_max: 'H2 最大值', xs: 'XS 间距', sm: 'S 间距', md: 'M 间距', lg: 'L 间距', xl: 'XL 间距', '2xl': '2XL 间距', '3xl': '3XL 间距', preset: '预设', max: '最大宽度', narrow: '窄容器', gutter_min: '最小边距', gutter_max: '最大边距', min_height: '最小高度', horizontal_padding: '水平内边距', radius: '按钮圆角', font_weight: '字重', line_height: '行高', gap: '区块间距' },
};

export const THEME_STUDIO_TRANSLATIONS: Record<AdminLocale, Readonly<Record<string, string>>> = {
  vi: { eyebrow: 'GIAO DIỆN PUBLIC', title: 'Public Theme Studio', description: 'Điều chỉnh token an toàn cho website public; không ảnh hưởng skin admin.', refresh: 'Tải lại', save: 'Lưu bản nháp', preview: 'Xem trước', publish: 'Xuất bản', versions: 'Lịch sử phiên bản', currentDraft: 'Bản nháp', currentPublished: 'Đang public', version: 'Phiên bản', publishedAt: 'Xuất bản lúc', rollback: 'Rollback', loading: 'Đang tải theme…', loadError: 'Không thể tải Public Theme Studio.', saveError: 'Không thể lưu bản nháp.', publishError: 'Không thể xuất bản theme.', rollbackError: 'Không thể rollback theme.', previewError: 'Không thể tạo URL preview.', saved: 'Đã lưu bản nháp theme.', published: 'Đã xuất bản theme.', rolledBack: 'Đã rollback theme.', confirmPublish: 'Xuất bản bản nháp hiện tại ra website public?', confirmRollback: 'Rollback website public về phiên bản này?', empty: 'Chưa có dữ liệu theme.', colors: 'Màu sắc', fonts: 'Font chữ', sizes: 'Cỡ chữ', spacing: 'Khoảng cách', radii: 'Bo góc', shadows: 'Đổ bóng', containers: 'Khung nội dung', buttons: 'Nút bấm', headings: 'Tiêu đề', sections: 'Section', animation: 'Chuyển động', px: 'px', system_sans: 'System Sans', serif: 'Serif', none: 'Không', soft: 'Nhẹ', raised: 'Nổi', subtle: 'Tinh tế', standard: 'Tiêu chuẩn', draftNotice: 'Preview dùng chính Blade renderer và compiler của trang public.', discarded: 'Đã bỏ', draft: 'Bản nháp', statusPublished: 'Đã xuất bản' },
  en: { eyebrow: 'PUBLIC APPEARANCE', title: 'Public Theme Studio', description: 'Adjust safe public website tokens without changing the admin skin.', refresh: 'Refresh', save: 'Save draft', preview: 'Preview', publish: 'Publish', versions: 'Version history', currentDraft: 'Draft', currentPublished: 'Live', version: 'Version', publishedAt: 'Published at', rollback: 'Rollback', loading: 'Loading theme…', loadError: 'Unable to load Public Theme Studio.', saveError: 'Unable to save the draft.', publishError: 'Unable to publish the theme.', rollbackError: 'Unable to roll back the theme.', previewError: 'Unable to create the preview URL.', saved: 'Theme draft saved.', published: 'Theme published.', rolledBack: 'Theme rolled back.', confirmPublish: 'Publish the current draft to the public website?', confirmRollback: 'Roll the public website back to this version?', empty: 'No theme data available.', colors: 'Colors', fonts: 'Fonts', sizes: 'Type sizes', spacing: 'Spacing', radii: 'Radii', shadows: 'Shadows', containers: 'Containers', buttons: 'Buttons', headings: 'Headings', sections: 'Sections', animation: 'Animation', px: 'px', system_sans: 'System Sans', serif: 'Serif', none: 'None', soft: 'Soft', raised: 'Raised', subtle: 'Subtle', standard: 'Standard', draftNotice: 'Preview uses the same Blade renderer and compiler as the public page.', discarded: 'Discarded', draft: 'Draft', statusPublished: 'Published' },
  zh: { eyebrow: '公开网站外观', title: '公开主题工作室', description: '安全调整公开网站令牌，不影响管理后台皮肤。', refresh: '刷新', save: '保存草稿', preview: '预览', publish: '发布', versions: '版本历史', currentDraft: '草稿', currentPublished: '线上版本', version: '版本', publishedAt: '发布时间', rollback: '回滚', loading: '正在加载主题…', loadError: '无法加载公开主题工作室。', saveError: '无法保存草稿。', publishError: '无法发布主题。', rollbackError: '无法回滚主题。', previewError: '无法创建预览链接。', saved: '主题草稿已保存。', published: '主题已发布。', rolledBack: '主题已回滚。', confirmPublish: '将当前草稿发布到公开网站？', confirmRollback: '将公开网站回滚到此版本？', empty: '暂无主题数据。', colors: '颜色', fonts: '字体', sizes: '字号', spacing: '间距', radii: '圆角', shadows: '阴影', containers: '容器', buttons: '按钮', headings: '标题', sections: '区块', animation: '动画', px: 'px', system_sans: '系统无衬线', serif: '衬线字体', none: '无', soft: '柔和', raised: '浮起', subtle: '细微', standard: '标准', draftNotice: '预览与公开页面使用相同的 Blade 渲染器和编译器。', discarded: '已废弃', draft: '草稿', statusPublished: '已发布' },
};

export function themeTokenName(locale: AdminLocale, key: string): string {
  return TOKEN_NAMES[locale][key] ?? key;
}
