server {
    listen 8080;
    listen [::]:8080;
    server_name hongvan.local;

    root /var/www/html/public;
    index index.php;
    charset utf-8;
    client_max_body_size 11m;

    add_header X-Content-Type-Options nosniff always;

    location /storage/ {
        alias /var/www/html/storage/app/public/;
        access_log off;
        expires 7d;
    }

    location ^~ /admin {
        try_files /__hongvan_admin_spa__ /index.php?$query_string;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_pass hongvan-php:9000;
        fastcgi_read_timeout 120s;
    }

    location ~ /\.(?!well-known(?:/|$)) {
        deny all;
    }

    location ~* \.(?:bak|conf|dist|env|ini|log|sql)$ {
        deny all;
    }
}
