import { AdminLocale } from '../../core/i18n/i18n.service';

type LeadDictionary = Readonly<Record<string, string>>;

export const LEAD_TRANSLATIONS: Readonly<Record<AdminLocale, LeadDictionary>> = {
  vi: {
    eyebrow: 'TIẾP NHẬN KHÁCH HÀNG', title: 'Hộp thư liên hệ & báo giá', subtitle: 'Một nơi xử lý liên hệ, báo giá sản phẩm, vận chuyển và thuê kho.', refresh: 'Làm mới', export: 'Xuất CSV', total: 'Tổng lead', unassigned: 'Chưa phân công', newToday: 'Mới hôm nay', allTypes: 'Tất cả loại', allStatuses: 'Tất cả trạng thái', allAssignments: 'Mọi phân công', mine: 'Của tôi', assigned: 'Đã phân công', contact: 'Liên hệ', product_quote: 'Báo giá sản phẩm', transport: 'Vận chuyển', warehouse: 'Kho bãi', new: 'Mới', contacted: 'Đã liên hệ', qualified: 'Đủ điều kiện', processing: 'Đang xử lý', done: 'Hoàn tất', spam: 'Spam', archived: 'Lưu trữ', empty: 'Chưa có lead phù hợp bộ lọc.', selectLead: 'Chọn một lead để xem và xử lý.', original: 'Nội dung gốc (chỉ đọc)', privacy: 'Đồng ý chính sách', assignment: 'Người phụ trách', status: 'Trạng thái', unassign: 'Chưa phân công', apply: 'Áp dụng', note: 'Ghi chú nội bộ', addNote: 'Thêm ghi chú', timeline: 'Lịch sử trạng thái', assignmentHistory: 'Lịch sử phân công', notes: 'Ghi chú', noNotes: 'Chưa có ghi chú.', loadError: 'Không thể tải hộp thư lead.', operationError: 'Không thể cập nhật lead.', updated: 'Đã cập nhật lead.', exported: 'Đã tải file CSV.', close: 'Đóng', immutable: 'Nội dung khách gửi được mã hóa và không thể chỉnh sửa.', contactInfo: 'Thông tin liên hệ', source: 'Nguồn', createdAt: 'Thời gian gửi', noTransition: 'Không còn bước chuyển trạng thái hợp lệ.'
  },
  en: {
    eyebrow: 'CUSTOMER INTAKE', title: 'Contact & quote inbox', subtitle: 'Handle contact, product quote, transportation and warehouse enquiries in one place.', refresh: 'Refresh', export: 'Export CSV', total: 'Total leads', unassigned: 'Unassigned', newToday: 'New today', allTypes: 'All types', allStatuses: 'All statuses', allAssignments: 'All assignments', mine: 'Mine', assigned: 'Assigned', contact: 'Contact', product_quote: 'Product quote', transport: 'Transportation', warehouse: 'Warehouse', new: 'New', contacted: 'Contacted', qualified: 'Qualified', processing: 'Processing', done: 'Done', spam: 'Spam', archived: 'Archived', empty: 'No leads match these filters.', selectLead: 'Select a lead to inspect and process.', original: 'Original submission (read only)', privacy: 'Privacy consent', assignment: 'Assignee', status: 'Status', unassign: 'Unassigned', apply: 'Apply', note: 'Internal note', addNote: 'Add note', timeline: 'Status timeline', assignmentHistory: 'Assignment history', notes: 'Notes', noNotes: 'No notes yet.', loadError: 'Unable to load the lead inbox.', operationError: 'Unable to update the lead.', updated: 'Lead updated.', exported: 'CSV downloaded.', close: 'Close', immutable: 'Customer content is encrypted and cannot be edited.', contactInfo: 'Contact details', source: 'Source', createdAt: 'Submitted at', noTransition: 'No further status transition is allowed.'
  },
  zh: {
    eyebrow: '客户接收', title: '联系与报价收件箱', subtitle: '统一处理联系、产品报价、运输和仓储咨询。', refresh: '刷新', export: '导出 CSV', total: '线索总数', unassigned: '未分配', newToday: '今日新增', allTypes: '所有类型', allStatuses: '所有状态', allAssignments: '所有分配', mine: '我的', assigned: '已分配', contact: '联系', product_quote: '产品报价', transport: '运输', warehouse: '仓储', new: '新建', contacted: '已联系', qualified: '已确认', processing: '处理中', done: '已完成', spam: '垃圾信息', archived: '已归档', empty: '没有符合筛选条件的线索。', selectLead: '选择一条线索查看并处理。', original: '原始提交（只读）', privacy: '隐私同意', assignment: '负责人', status: '状态', unassign: '未分配', apply: '应用', note: '内部备注', addNote: '添加备注', timeline: '状态时间线', assignmentHistory: '分配历史', notes: '备注', noNotes: '暂无备注。', loadError: '无法加载线索收件箱。', operationError: '无法更新线索。', updated: '线索已更新。', exported: 'CSV 已下载。', close: '关闭', immutable: '客户内容已加密且无法编辑。', contactInfo: '联系信息', source: '来源', createdAt: '提交时间', noTransition: '没有可用的后续状态。'
  },
};
