<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('hongvan_media_folders', function (Blueprint $table): void {
            $table->comment('Logical folders used to organize media independently from the configured storage disk');
            $table->id()->comment('Internal primary key of the media folder');
            $table->char('public_id', 26)->unique()->comment('Public ULID used to identify the folder in Admin APIs');
            $table->foreignId('parent_id')->nullable()->comment('Optional parent folder used to build a logical hierarchy')->constrained('hongvan_media_folders')->nullOnDelete();
            $table->string('name')->comment('Administrator-facing folder name');
            $table->string('slug', 191)->comment('Normalized folder segment generated by the server');
            $table->unsignedSmallInteger('sort_order')->default(0)->index()->comment('Ascending display order inside the parent folder');
            $table->foreignId('created_by')->nullable()->comment('Administrator who created the folder; null for system operations')->constrained('hongvan_users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('Administrator who most recently changed the folder')->constrained('hongvan_users')->nullOnDelete();
            $table->timestamp('deleted_at')->nullable()->index()->comment('UTC time when the folder was moved to trash; null while active');
            $table->timestamp('created_at')->nullable()->comment('UTC time when the folder was created');
            $table->timestamp('updated_at')->nullable()->comment('UTC time when the folder was most recently updated');

            $table->index(['parent_id', 'slug']);
        });

        Schema::create('hongvan_media', function (Blueprint $table): void {
            $table->comment('Storage-independent media records containing safe file metadata without a fixed public URL');
            $table->id()->comment('Internal primary key of the media record');
            $table->char('public_id', 26)->unique()->comment('Public ULID used to identify media in APIs and storage paths');
            $table->foreignId('folder_id')->nullable()->comment('Logical media folder; null means the root library')->constrained('hongvan_media_folders')->nullOnDelete();
            $table->string('disk', 64)->comment('Laravel Filesystem disk that owns the original object');
            $table->string('path', 500)->unique()->comment('Server-generated path of the original object relative to its disk');
            $table->string('original_filename')->comment('Original client filename retained only as display metadata');
            $table->string('normalized_filename')->comment('Safe normalized display filename generated by the server');
            $table->string('extension', 16)->comment('Lowercase extension accepted by the server allowlist');
            $table->string('mime_type', 127)->index()->comment('MIME type detected from the actual uploaded bytes');
            $table->unsignedBigInteger('size_bytes')->comment('Original object size in bytes');
            $table->char('checksum_sha256', 64)->index()->comment('SHA-256 checksum of the original object for integrity and duplicate detection');
            $table->unsignedInteger('width')->nullable()->comment('Decoded original image width in pixels; null for non-image media');
            $table->unsignedInteger('height')->nullable()->comment('Decoded original image height in pixels; null for non-image media');
            $table->string('status', 32)->default('processing')->index()->comment('Lifecycle status: processing, ready, failed, or trashed');
            $table->string('visibility', 16)->default('private')->comment('Storage intent: private or public; URL is always resolved at runtime');
            $table->string('title')->nullable()->comment('Optional administrator-defined media title');
            $table->string('alt_text')->nullable()->comment('Alternative text for accessible image usage');
            $table->text('caption')->nullable()->comment('Optional descriptive caption for consuming modules');
            $table->json('metadata')->nullable()->comment('Allowlisted technical metadata that does not contain file bodies or secrets');
            $table->foreignId('uploaded_by')->nullable()->comment('Administrator who uploaded the original object')->constrained('hongvan_users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('Administrator who most recently updated media metadata')->constrained('hongvan_users')->nullOnDelete();
            $table->foreignId('deleted_by')->nullable()->comment('Administrator who moved the media to trash')->constrained('hongvan_users')->nullOnDelete();
            $table->timestamp('deleted_at')->nullable()->index()->comment('UTC time when media was moved to trash; null while active');
            $table->timestamp('created_at')->nullable()->comment('UTC time when the media record was created');
            $table->timestamp('updated_at')->nullable()->comment('UTC time when the media record was most recently updated');

            $table->index(['folder_id', 'status', 'created_at']);
        });

        Schema::create('hongvan_media_variants', function (Blueprint $table): void {
            $table->comment('Queued derivative image files such as thumbnails, WebP, and AVIF variants');
            $table->id()->comment('Internal primary key of the media variant');
            $table->char('public_id', 26)->unique()->comment('Public ULID of the generated variant');
            $table->foreignId('media_id')->comment('Original media record that owns this derivative')->constrained('hongvan_media')->cascadeOnDelete();
            $table->string('variant_key', 64)->comment('Stable variant key combining size purpose and output format');
            $table->string('disk', 64)->comment('Laravel Filesystem disk that owns the derivative object');
            $table->string('path', 500)->unique()->comment('Server-generated derivative path relative to its disk');
            $table->string('extension', 16)->comment('Lowercase output extension produced by the image encoder');
            $table->string('mime_type', 127)->comment('MIME type of the encoded derivative bytes');
            $table->unsignedBigInteger('size_bytes')->comment('Derivative object size in bytes');
            $table->char('checksum_sha256', 64)->comment('SHA-256 checksum of the derivative object');
            $table->unsignedInteger('width')->comment('Decoded derivative width in pixels');
            $table->unsignedInteger('height')->comment('Decoded derivative height in pixels');
            $table->string('status', 32)->default('ready')->index()->comment('Derivative generation status: ready or failed');
            $table->text('error_message')->nullable()->comment('Sanitized generation failure summary without file contents or secrets');
            $table->timestamp('generated_at')->nullable()->comment('UTC time when the derivative was successfully generated');
            $table->timestamp('created_at')->nullable()->comment('UTC time when the variant row was created');
            $table->timestamp('updated_at')->nullable()->comment('UTC time when the variant row was most recently updated');

            $table->unique(['media_id', 'variant_key']);
        });

        Schema::create('hongvan_media_tags', function (Blueprint $table): void {
            $table->comment('Reusable normalized tags for searching and grouping media');
            $table->id()->comment('Internal primary key of the media tag');
            $table->char('public_id', 26)->unique()->comment('Public ULID of the media tag');
            $table->string('name')->comment('Administrator-facing tag name');
            $table->string('slug', 191)->unique()->comment('Unique normalized tag identifier generated by the server');
            $table->timestamp('created_at')->nullable()->comment('UTC time when the tag was created');
            $table->timestamp('updated_at')->nullable()->comment('UTC time when the tag was most recently updated');
        });

        Schema::create('hongvan_media_tag_links', function (Blueprint $table): void {
            $table->comment('Pivot assignments connecting media records to reusable tags');
            $table->foreignId('media_id')->comment('Media record assigned to the tag')->constrained('hongvan_media')->cascadeOnDelete();
            $table->foreignId('media_tag_id')->comment('Tag assigned to the media record')->constrained('hongvan_media_tags')->cascadeOnDelete();
            $table->timestamp('created_at')->nullable()->comment('UTC time when the media-tag assignment was created');

            $table->primary(['media_id', 'media_tag_id']);
        });

        Schema::create('hongvan_media_usages', function (Blueprint $table): void {
            $table->comment('Usage registry preventing unsafe deletion of media referenced by business modules');
            $table->id()->comment('Internal primary key of the media usage');
            $table->char('public_id', 26)->unique()->comment('Public ULID of the usage record');
            $table->foreignId('media_id')->comment('Media record referenced by another module')->constrained('hongvan_media')->cascadeOnDelete();
            $table->string('owner_type', 100)->comment('Allowlisted business owner type such as product, page, post, or settings');
            $table->char('owner_public_id', 26)->comment('Public ULID or stable settings identifier of the owning record');
            $table->string('field', 100)->comment('Owner field or slot that references the media');
            $table->json('metadata')->nullable()->comment('Non-sensitive usage context used for diagnostics and safe delete warnings');
            $table->timestamp('created_at')->nullable()->comment('UTC time when the usage was first registered');
            $table->timestamp('updated_at')->nullable()->comment('UTC time when the usage metadata was most recently refreshed');

            $table->unique(['media_id', 'owner_type', 'owner_public_id', 'field'], 'hongvan_media_usages_owner_unique');
            $table->index(['owner_type', 'owner_public_id']);
        });

        Schema::create('hongvan_media_operations', function (Blueprint $table): void {
            $table->comment('Retryable lifecycle and variant operations for media processing, cleanup, and diagnostics');
            $table->id()->comment('Internal primary key of the media operation');
            $table->char('public_id', 26)->unique()->comment('Public ULID of the operation record');
            $table->foreignId('media_id')->nullable()->comment('Current media row; null after an audited permanent cleanup')->constrained('hongvan_media')->nullOnDelete();
            $table->char('media_public_id', 26)->index()->comment('Immutable media ULID snapshot retained if the media row is deleted');
            $table->string('operation', 64)->index()->comment('Operation key such as variant_generation, cleanup, or retry');
            $table->string('status', 32)->index()->comment('Operation state: queued, processing, completed, or failed');
            $table->unsignedSmallInteger('attempts')->default(0)->comment('Number of processing attempts recorded for this operation');
            $table->string('queue', 64)->nullable()->comment('Queue name used for asynchronous processing');
            $table->json('metadata')->nullable()->comment('Allowlisted operation metadata without file bodies or secrets');
            $table->text('error_message')->nullable()->comment('Sanitized latest failure summary used for retry diagnostics');
            $table->timestamp('started_at')->nullable()->comment('UTC time when the current processing attempt started');
            $table->timestamp('finished_at')->nullable()->comment('UTC time when the operation completed or failed');
            $table->timestamp('created_at')->nullable()->comment('UTC time when the operation was queued');
            $table->timestamp('updated_at')->nullable()->comment('UTC time when the operation state was most recently updated');

            $table->index(['media_id', 'operation', 'status']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('hongvan_media_operations');
        Schema::dropIfExists('hongvan_media_usages');
        Schema::dropIfExists('hongvan_media_tag_links');
        Schema::dropIfExists('hongvan_media_tags');
        Schema::dropIfExists('hongvan_media_variants');
        Schema::dropIfExists('hongvan_media');
        Schema::dropIfExists('hongvan_media_folders');
    }
};
