import { AdminLocale } from '../../core/i18n/i18n.service';

export const LOCALIZATION_TRANSLATIONS: Record<AdminLocale, Readonly<Record<string, string>>> = {
  vi: {
    eyebrow: 'NỀN TẢNG NỘI DUNG', title: 'Đa ngôn ngữ & múi giờ', description: 'Quản lý ngôn ngữ public, chuỗi fallback và báo cáo bản dịch còn thiếu.', storageTimezone: 'Múi giờ lưu trữ', displayTimezone: 'Múi giờ hiển thị', generatedAt: 'Thời điểm báo cáo', translationKeys: 'Khóa bản dịch', languages: 'Ngôn ngữ', active: 'Đang hoạt động', inactive: 'Đã tắt', default: 'Mặc định', makeDefault: 'Đặt mặc định', fallback: 'Ngôn ngữ dự phòng', noFallback: 'Dùng ngôn ngữ mặc định', fallbackHelp: 'Dùng khi nội dung của locale này bị thiếu.', missingReport: 'Báo cáo bản dịch thiếu', missing: 'thiếu', complete: 'Đầy đủ', noKeys: 'Chưa có khóa bản dịch trong database.', saved: 'Đã cập nhật cấu hình ngôn ngữ.', loadError: 'Không thể tải cấu hình đa ngôn ngữ.', saveError: 'Không thể cập nhật ngôn ngữ.', systemRule: 'Tiếng Việt là mặc định; dữ liệu thời gian lưu UTC và hiển thị theo giờ Việt Nam.', updatedAt: 'Cập nhật', disabledRoute: 'Ngôn ngữ tắt sẽ chuyển về route tiếng Việt, không tạo trang lỗi.',
  },
  en: {
    eyebrow: 'CONTENT FOUNDATION', title: 'Localization & timezone', description: 'Manage public languages, fallback chains and missing-translation reporting.', storageTimezone: 'Storage timezone', displayTimezone: 'Display timezone', generatedAt: 'Report generated', translationKeys: 'Translation keys', languages: 'Languages', active: 'Active', inactive: 'Disabled', default: 'Default', makeDefault: 'Make default', fallback: 'Fallback language', noFallback: 'Use default language', fallbackHelp: 'Used when content is missing in this locale.', missingReport: 'Missing translations', missing: 'missing', complete: 'Complete', noKeys: 'No database translation keys yet.', saved: 'Language settings updated.', loadError: 'Unable to load localization settings.', saveError: 'Unable to update the language.', systemRule: 'Vietnamese is the default; timestamps are stored in UTC and displayed in Vietnam time.', updatedAt: 'Updated', disabledRoute: 'Disabled languages redirect to the Vietnamese route instead of producing an error.',
  },
  zh: {
    eyebrow: '内容基础', title: '多语言与时区', description: '管理公共语言、备用语言链和缺失翻译报告。', storageTimezone: '存储时区', displayTimezone: '显示时区', generatedAt: '报告生成时间', translationKeys: '翻译键', languages: '语言', active: '已启用', inactive: '已停用', default: '默认', makeDefault: '设为默认', fallback: '备用语言', noFallback: '使用默认语言', fallbackHelp: '当前 locale 缺少内容时使用。', missingReport: '缺失翻译报告', missing: '项缺失', complete: '完整', noKeys: '数据库中尚无翻译键。', saved: '语言设置已更新。', loadError: '无法加载多语言设置。', saveError: '无法更新语言。', systemRule: '越南语为默认语言；时间以 UTC 存储，并按越南时区显示。', updatedAt: '更新时间', disabledRoute: '停用的语言会跳转到越南语路由，不会显示错误页面。',
  },
};
