import { AdminLocale } from '../../core/i18n/i18n.service';

export const AUDIT_TRANSLATIONS: Record<AdminLocale, Readonly<Record<string, string>>> = {
  vi: {
    eyebrow: 'AN TOÀN HỆ THỐNG', title: 'Nhật ký thao tác', description: 'Theo dõi các hành động quản trị và sự kiện bảo mật đã được loại bỏ dữ liệu nhạy cảm.', action: 'Hành động', actor: 'Người thực hiện', subjectType: 'Loại đối tượng', requestId: 'Request ID', dateFrom: 'Từ ngày', dateTo: 'Đến ngày', apply: 'Áp dụng', reset: 'Xóa bộ lọc', loadError: 'Không thể tải nhật ký thao tác.', empty: 'Không có bản ghi phù hợp.', total: 'Tổng bản ghi', page: 'Trang', previous: 'Trang trước', next: 'Trang sau', occurredAt: 'Thời điểm', subject: 'Đối tượng', anonymous: 'Khách', system: 'Hệ thống', before: 'Trước thay đổi', after: 'Sau thay đổi', metadata: 'Metadata an toàn', fingerprints: 'Dấu vân tay bảo mật', immutable: 'Audit log là append-only; giao diện này không hỗ trợ sửa hoặc xóa.', noDiff: 'Sự kiện không có dữ liệu chênh lệch.', refresh: 'Làm mới', of: 'trên', actorId: 'ULID người thực hiện', requestHint: 'ULID của request', subjectHint: 'Ví dụ: user, role, company_settings', actionHint: 'Ví dụ: identity.user.updated', details: 'Chi tiết', redacted: 'Password, token, cookie, secret và nội dung file luôn được redaction.',
  },
  en: {
    eyebrow: 'SYSTEM SECURITY', title: 'Audit log', description: 'Review administrative actions and security events after sensitive data has been removed.', action: 'Action', actor: 'Actor', subjectType: 'Subject type', requestId: 'Request ID', dateFrom: 'From date', dateTo: 'To date', apply: 'Apply', reset: 'Clear filters', loadError: 'Unable to load the audit log.', empty: 'No matching records.', total: 'Total records', page: 'Page', previous: 'Previous page', next: 'Next page', occurredAt: 'Occurred at', subject: 'Subject', anonymous: 'Anonymous', system: 'System', before: 'Before change', after: 'After change', metadata: 'Safe metadata', fingerprints: 'Security fingerprints', immutable: 'Audit logs are append-only; this screen does not support editing or deletion.', noDiff: 'This event has no change data.', refresh: 'Refresh', of: 'of', actorId: 'Actor ULID', requestHint: 'Request ULID', subjectHint: 'Example: user, role, company_settings', actionHint: 'Example: identity.user.updated', details: 'Details', redacted: 'Passwords, tokens, cookies, secrets and file contents are always redacted.',
  },
  zh: {
    eyebrow: '系统安全', title: '操作日志', description: '查看已移除敏感数据的管理操作和安全事件。', action: '操作', actor: '操作人', subjectType: '对象类型', requestId: '请求 ID', dateFrom: '开始日期', dateTo: '结束日期', apply: '应用', reset: '清除筛选', loadError: '无法加载操作日志。', empty: '没有符合条件的记录。', total: '记录总数', page: '页', previous: '上一页', next: '下一页', occurredAt: '发生时间', subject: '对象', anonymous: '匿名用户', system: '系统', before: '变更前', after: '变更后', metadata: '安全元数据', fingerprints: '安全指纹', immutable: '审计日志仅允许追加；此页面不支持编辑或删除。', noDiff: '此事件没有差异数据。', refresh: '刷新', of: '共', actorId: '操作人 ULID', requestHint: '请求 ULID', subjectHint: '例如：user、role、company_settings', actionHint: '例如：identity.user.updated', details: '详情', redacted: '密码、令牌、Cookie、密钥和文件内容始终会被脱敏。',
  },
};
