import { AdminLocale } from '../../core/i18n/i18n.service';

export const CROP_SOLUTION_TRANSLATIONS: Record<AdminLocale, Readonly<Record<string, string>>> = {
  vi: {
    eyebrow: 'NỘI DUNG NÔNG NGHIỆP', title: 'Giải pháp cây trồng', description: 'Quản lý cây trồng, timeline giai đoạn, nội dung giải pháp và sản phẩm đề xuất.',
    solutions: 'Giải pháp', crops: 'Cây trồng', stages: 'Giai đoạn', categories: 'Nhóm cây trồng', addSolution: 'Thêm giải pháp', addCrop: 'Thêm cây trồng', addStage: 'Thêm giai đoạn', addCategory: 'Thêm nhóm', refresh: 'Làm mới',
    search: 'Tìm giải pháp', status: 'Trạng thái', allStatuses: 'Tất cả trạng thái', crop: 'Cây trồng', allCrops: 'Tất cả cây trồng', stage: 'Giai đoạn', allStages: 'Tất cả giai đoạn', apply: 'Áp dụng', clear: 'Xóa lọc',
    loading: 'Đang tải dữ liệu cây trồng...', loadError: 'Không thể tải dữ liệu giải pháp cây trồng.', emptySolutions: 'Chưa có giải pháp phù hợp.', emptyReferences: 'Chưa có dữ liệu.', code: 'Mã', name: 'Tên', order: 'Thứ tự', active: 'Đang hoạt động', actions: 'Thao tác', edit: 'Chỉnh sửa', delete: 'Xóa', publish: 'Xuất bản', archive: 'Lưu trữ', previewPending: 'Public frontend được triển khai ở bước cuối.', featured: 'Nổi bật', products: 'Sản phẩm đề xuất',
    draft: 'Bản nháp', published: 'Đã xuất bản', scheduled: 'Đã lên lịch', archived: 'Đã lưu trữ', save: 'Lưu', saving: 'Đang lưu...', cancel: 'Hủy', close: 'Đóng', created: 'Đã tạo dữ liệu.', updated: 'Đã cập nhật dữ liệu.', deleted: 'Đã xóa dữ liệu.', operationError: 'Thao tác thất bại.', confirmDelete: 'Bạn chắc chắn muốn xóa mục này?',
    createReference: 'Tạo dữ liệu cây trồng', editReference: 'Chỉnh sửa dữ liệu cây trồng', parentCategory: 'Nhóm cha', category: 'Nhóm cây trồng', noSelection: 'Không chọn', image: 'Hình ảnh', chooseImage: 'Chọn hình ảnh', languageVi: 'Tiếng Việt', languageEn: 'Tiếng Anh', languageZh: 'Tiếng Trung', slug: 'Slug', summary: 'Mô tả ngắn', content: 'Nội dung', descriptionField: 'Mô tả chi tiết', metaTitle: 'SEO title dự phòng', metaDescription: 'SEO description dự phòng', requiredField: 'Trường này là bắt buộc.',
    createSolution: 'Tạo giải pháp cây trồng', editSolution: 'Chỉnh sửa giải pháp cây trồng', general: 'Thông tin chung', localizedContent: 'Nội dung đa ngôn ngữ', publishing: 'Xuất bản', heroImage: 'Ảnh đại diện', sectionLines: 'Các phần nội dung', sectionLinesHint: 'Mỗi dòng theo định dạng: Tiêu đề | Nội dung', recommendedProducts: 'Sản phẩm đề xuất', productHint: 'Sản phẩm archived/deleted sẽ tự bị loại khỏi dữ liệu public.', publishedAt: 'Bắt đầu xuất bản', unpublishedAt: 'Kết thúc xuất bản', noFakeAdvice: 'Chỉ nhập nội dung đã được doanh nghiệp kiểm duyệt; không tạo khuyến cáo tuyệt đối hoặc số liệu chuyên môn chưa xác minh.',
  },
  en: {
    eyebrow: 'AGRICULTURAL CONTENT', title: 'Crop solutions', description: 'Manage crops, stage timelines, solution content and recommended products.',
    solutions: 'Solutions', crops: 'Crops', stages: 'Stages', categories: 'Crop groups', addSolution: 'Add solution', addCrop: 'Add crop', addStage: 'Add stage', addCategory: 'Add group', refresh: 'Refresh',
    search: 'Search solutions', status: 'Status', allStatuses: 'All statuses', crop: 'Crop', allCrops: 'All crops', stage: 'Stage', allStages: 'All stages', apply: 'Apply', clear: 'Clear filters',
    loading: 'Loading crop data...', loadError: 'Unable to load crop solution data.', emptySolutions: 'No matching solutions.', emptyReferences: 'No data available.', code: 'Code', name: 'Name', order: 'Order', active: 'Active', actions: 'Actions', edit: 'Edit', delete: 'Delete', publish: 'Publish', archive: 'Archive', previewPending: 'Public frontend is delivered in the final stage.', featured: 'Featured', products: 'Recommended products',
    draft: 'Draft', published: 'Published', scheduled: 'Scheduled', archived: 'Archived', save: 'Save', saving: 'Saving...', cancel: 'Cancel', close: 'Close', created: 'Data created.', updated: 'Data updated.', deleted: 'Data deleted.', operationError: 'The operation failed.', confirmDelete: 'Are you sure you want to delete this item?',
    createReference: 'Create crop data', editReference: 'Edit crop data', parentCategory: 'Parent group', category: 'Crop group', noSelection: 'None', image: 'Image', chooseImage: 'Choose image', languageVi: 'Vietnamese', languageEn: 'English', languageZh: 'Chinese', slug: 'Slug', summary: 'Summary', content: 'Content', descriptionField: 'Detailed description', metaTitle: 'SEO title preparation', metaDescription: 'SEO description preparation', requiredField: 'This field is required.',
    createSolution: 'Create crop solution', editSolution: 'Edit crop solution', general: 'General', localizedContent: 'Localized content', publishing: 'Publishing', heroImage: 'Hero image', sectionLines: 'Content sections', sectionLinesHint: 'One section per line: Title | Body', recommendedProducts: 'Recommended products', productHint: 'Archived or deleted products are automatically excluded from public data.', publishedAt: 'Publish from', unpublishedAt: 'Publish until', noFakeAdvice: 'Only enter business-reviewed content; do not add absolute recommendations or unverified technical figures.',
  },
  zh: {
    eyebrow: '农业内容', title: '作物解决方案', description: '管理作物、阶段时间线、解决方案内容和推荐产品。',
    solutions: '解决方案', crops: '作物', stages: '阶段', categories: '作物分类', addSolution: '添加解决方案', addCrop: '添加作物', addStage: '添加阶段', addCategory: '添加分类', refresh: '刷新',
    search: '搜索解决方案', status: '状态', allStatuses: '全部状态', crop: '作物', allCrops: '全部作物', stage: '阶段', allStages: '全部阶段', apply: '应用', clear: '清除筛选',
    loading: '正在加载作物数据...', loadError: '无法加载作物解决方案数据。', emptySolutions: '没有匹配的解决方案。', emptyReferences: '暂无数据。', code: '编码', name: '名称', order: '顺序', active: '启用', actions: '操作', edit: '编辑', delete: '删除', publish: '发布', archive: '归档', previewPending: '公共前端将在最后阶段交付。', featured: '推荐', products: '推荐产品',
    draft: '草稿', published: '已发布', scheduled: '已计划', archived: '已归档', save: '保存', saving: '保存中...', cancel: '取消', close: '关闭', created: '数据已创建。', updated: '数据已更新。', deleted: '数据已删除。', operationError: '操作失败。', confirmDelete: '确定要删除此项目吗？',
    createReference: '创建作物数据', editReference: '编辑作物数据', parentCategory: '父分类', category: '作物分类', noSelection: '不选择', image: '图片', chooseImage: '选择图片', languageVi: '越南语', languageEn: '英语', languageZh: '中文', slug: 'Slug', summary: '简短描述', content: '内容', descriptionField: '详细描述', metaTitle: 'SEO 标题预设', metaDescription: 'SEO 描述预设', requiredField: '此字段为必填项。',
    createSolution: '创建作物解决方案', editSolution: '编辑作物解决方案', general: '基本信息', localizedContent: '多语言内容', publishing: '发布', heroImage: '主图', sectionLines: '内容区块', sectionLinesHint: '每行一个区块：标题 | 内容', recommendedProducts: '推荐产品', productHint: '已归档或删除的产品会自动从公共数据中移除。', publishedAt: '开始发布', unpublishedAt: '结束发布', noFakeAdvice: '仅输入经企业审核的内容；不得添加绝对建议或未经核实的技术数据。',
  },
};
