import { AdminLocale } from '../../core/i18n/i18n.service';

export const SEO_TOOLS_TRANSLATIONS: Record<AdminLocale, Readonly<Record<string, string>>> = {
  vi: {
    title: 'SEO kỹ thuật', redirects: 'Chuyển hướng URL', redirectHelp: 'Chỉ áp dụng chính xác đường dẫn nguồn; hệ thống tự chặn xung đột và vòng lặp.',
    newRule: 'Thêm quy tắc', source: 'Đường dẫn nguồn', target: 'Đường dẫn đích', locale: 'Ngôn ngữ', allLocales: 'Tất cả', status: 'Mã phản hồi', active: 'Đang hoạt động', note: 'Ghi chú nội bộ', save: 'Lưu quy tắc', cancel: 'Hủy sửa', edit: 'Sửa', delete: 'Xóa', noRedirects: 'Chưa có quy tắc chuyển hướng.', hits: 'Lượt dùng', confirmDelete: 'Xóa quy tắc chuyển hướng này?',
    technical: 'Sitemap, robots.txt & schema', sitemapHealth: 'Tình trạng sitemap', generatedAt: 'Tạo gần nhất', shards: 'Sitemap con', urls: 'URL hợp lệ', notGenerated: 'Chưa tạo', regenerate: 'Tạo lại sitemap', robots: 'Đường dẫn chặn trong robots.txt', robotsHint: 'Mỗi dòng là một đường dẫn nội bộ bắt đầu bằng /.', saveRobots: 'Lưu robots.txt', schema: 'Xem trước structured data', schemaType: 'Loại schema', preview: 'Xem trước', organization: 'Organization', local_business: 'LocalBusiness', website: 'WebSite', noSchema: 'Chưa đủ dữ liệu thật để tạo schema này.', loading: 'Đang tải…', saved: 'Đã lưu thay đổi.', queued: 'Đã đưa sitemap vào hàng đợi tạo lại.', loadError: 'Không thể tải công cụ SEO.', saveError: 'Không thể lưu thay đổi.', indexingOff: 'Website đang tắt public indexing.', indexingOn: 'Website đang cho phép public indexing.', metadataTab: 'Metadata nội dung', toolsTab: 'SEO kỹ thuật', open: 'Mở', vi: 'Tiếng Việt', en: 'English', zh: '中文', gone: '410 Gone', permanent: '301 Vĩnh viễn', temporary: '302 Tạm thời',
  },
  en: {
    title: 'Technical SEO', redirects: 'URL redirects', redirectHelp: 'Rules match the exact source path; collisions and loops are blocked automatically.', newRule: 'Add rule', source: 'Source path', target: 'Target path', locale: 'Locale', allLocales: 'All locales', status: 'Response code', active: 'Active', note: 'Internal note', save: 'Save rule', cancel: 'Cancel edit', edit: 'Edit', delete: 'Delete', noRedirects: 'No redirect rules yet.', hits: 'Hits', confirmDelete: 'Delete this redirect rule?', technical: 'Sitemap, robots.txt & schema', sitemapHealth: 'Sitemap health', generatedAt: 'Last generated', shards: 'Sitemap shards', urls: 'Eligible URLs', notGenerated: 'Not generated yet', regenerate: 'Regenerate sitemap', robots: 'Disallowed paths in robots.txt', robotsHint: 'Enter one internal path beginning with / per line.', saveRobots: 'Save robots.txt', schema: 'Structured data preview', schemaType: 'Schema type', preview: 'Preview', organization: 'Organization', local_business: 'LocalBusiness', website: 'WebSite', noSchema: 'There is not enough real data to build this schema.', loading: 'Loading…', saved: 'Changes saved.', queued: 'Sitemap regeneration queued.', loadError: 'Unable to load SEO tools.', saveError: 'Unable to save changes.', indexingOff: 'Public indexing is disabled.', indexingOn: 'Public indexing is enabled.', metadataTab: 'Content metadata', toolsTab: 'Technical SEO', open: 'Open', vi: 'Vietnamese', en: 'English', zh: '中文', gone: '410 Gone', permanent: '301 Permanent', temporary: '302 Temporary',
  },
  zh: {
    title: '技术 SEO', redirects: 'URL 重定向', redirectHelp: '规则仅匹配准确的源路径；系统会自动阻止冲突和循环。', newRule: '添加规则', source: '源路径', target: '目标路径', locale: '语言', allLocales: '所有语言', status: '响应代码', active: '启用', note: '内部备注', save: '保存规则', cancel: '取消编辑', edit: '编辑', delete: '删除', noRedirects: '暂无重定向规则。', hits: '访问次数', confirmDelete: '删除此重定向规则？', technical: 'Sitemap、robots.txt 与 schema', sitemapHealth: 'Sitemap 状态', generatedAt: '最近生成', shards: '子 Sitemap', urls: '有效 URL', notGenerated: '尚未生成', regenerate: '重新生成 Sitemap', robots: 'robots.txt 禁止路径', robotsHint: '每行输入一个以 / 开头的内部路径。', saveRobots: '保存 robots.txt', schema: '结构化数据预览', schemaType: 'Schema 类型', preview: '预览', organization: 'Organization', local_business: 'LocalBusiness', website: 'WebSite', noSchema: '真实数据不足，无法生成此 schema。', loading: '加载中…', saved: '更改已保存。', queued: 'Sitemap 重新生成任务已排队。', loadError: '无法加载 SEO 工具。', saveError: '无法保存更改。', indexingOff: '公开索引已关闭。', indexingOn: '公开索引已开启。', metadataTab: '内容元数据', toolsTab: '技术 SEO', open: '打开', vi: '越南语', en: 'English', zh: '中文', gone: '410 Gone', permanent: '301 永久', temporary: '302 临时',
  },
};
