import { AdminLocale } from '../../core/i18n/i18n.service';

export const SEO_TRANSLATIONS: Record<AdminLocale, Readonly<Record<string, string>>> = {
  vi: {
    eyebrow: 'TỐI ƯU TÌM KIẾM', title: 'SEO & chia sẻ mạng xã hội', description: 'Quản lý metadata theo từng nội dung và từng ngôn ngữ.', contentType: 'Loại nội dung', content: 'Nội dung', language: 'Ngôn ngữ', search: 'Tìm nội dung', refresh: 'Tải lại', selectContent: 'Chọn một nội dung để chỉnh sửa SEO.', empty: 'Không tìm thấy nội dung.', loadError: 'Không thể tải dữ liệu SEO.', saveError: 'Không thể lưu metadata SEO.', saved: 'Đã lưu metadata SEO.', save: 'Lưu thay đổi', searchResult: 'Kết quả tìm kiếm', socialPreview: 'Xem trước mạng xã hội', basic: 'Metadata tìm kiếm', social: 'Open Graph & Twitter', advanced: 'Nâng cao', metaTitle: 'Tiêu đề SEO', metaDescription: 'Mô tả SEO', canonical: 'Canonical URL tùy chỉnh', canonicalHint: 'Để trống để dùng URL được sinh từ route public.', index: 'Cho phép index khi nội dung đã xuất bản', follow: 'Cho phép crawler theo liên kết', ogTitle: 'Open Graph title', ogDescription: 'Open Graph description', ogType: 'Open Graph type', twitterCard: 'Twitter card', twitterTitle: 'Twitter title', twitterDescription: 'Twitter description', image: 'Ảnh chia sẻ', chooseImage: 'Chọn ảnh', removeImage: 'Bỏ ảnh', focusKeywords: 'Từ khóa trọng tâm', focusHint: 'Phân cách bằng dấu phẩy; chỉ dùng để biên tập, không sinh meta keywords.', titleGuide: 'Khuyến nghị 50–60 ký tự', descriptionGuide: 'Khuyến nghị 140–160 ký tự', noTitle: 'Tiêu đề sẽ dùng dữ liệu fallback', noDescription: 'Mô tả sẽ dùng dữ liệu fallback', product: 'Sản phẩm', crop_solution: 'Giải pháp cây trồng', service: 'Dịch vụ', post: 'Bài viết', project: 'Dự án', gallery: 'Thư viện ảnh', certification: 'Chứng nhận', vehicle: 'Phương tiện', transport_route: 'Tuyến vận chuyển', transport_service_area: 'Khu vực phục vụ', warehouse: 'Kho bãi', website: 'Website', article: 'Bài viết', summary: 'Tóm tắt', summary_large_image: 'Tóm tắt với ảnh lớn', vi: 'Tiếng Việt', en: 'English', zh: '中文', draftWarning: 'Draft, preview và trang admin luôn bị noindex.', loading: 'Đang tải…', status: 'Trạng thái', code: 'Mã', invalidCanonical: 'Canonical phải là URL HTTP hoặc HTTPS hợp lệ.', imageHint: 'Chỉ chọn ảnh public đã xử lý xong; hệ thống ưu tiên variant lớn nhất.', selectFirst: 'Hãy chọn nội dung ở cột bên trái.',
  },
  en: {
    eyebrow: 'SEARCH OPTIMIZATION', title: 'SEO & social sharing', description: 'Manage metadata for each content item and locale.', contentType: 'Content type', content: 'Content', language: 'Language', search: 'Search content', refresh: 'Refresh', selectContent: 'Select content to edit its SEO metadata.', empty: 'No content found.', loadError: 'Unable to load SEO data.', saveError: 'Unable to save SEO metadata.', saved: 'SEO metadata saved.', save: 'Save changes', searchResult: 'Search result', socialPreview: 'Social preview', basic: 'Search metadata', social: 'Open Graph & Twitter', advanced: 'Advanced', metaTitle: 'SEO title', metaDescription: 'SEO description', canonical: 'Custom canonical URL', canonicalHint: 'Leave empty to use the URL generated from the public route.', index: 'Allow indexing when content is published', follow: 'Allow crawlers to follow links', ogTitle: 'Open Graph title', ogDescription: 'Open Graph description', ogType: 'Open Graph type', twitterCard: 'Twitter card', twitterTitle: 'Twitter title', twitterDescription: 'Twitter description', image: 'Share image', chooseImage: 'Choose image', removeImage: 'Remove image', focusKeywords: 'Focus keywords', focusHint: 'Comma-separated editorial hints; no meta keywords tag is generated.', titleGuide: 'Recommended 50–60 characters', descriptionGuide: 'Recommended 140–160 characters', noTitle: 'The fallback title will be used', noDescription: 'The fallback description will be used', product: 'Products', crop_solution: 'Crop solutions', service: 'Services', post: 'Posts', project: 'Projects', gallery: 'Galleries', certification: 'Certifications', vehicle: 'Vehicles', transport_route: 'Transport routes', transport_service_area: 'Service areas', warehouse: 'Warehouses', website: 'Website', article: 'Article', summary: 'Summary', summary_large_image: 'Summary with large image', vi: 'Vietnamese', en: 'English', zh: '中文', draftWarning: 'Drafts, previews, and admin pages are always noindex.', loading: 'Loading…', status: 'Status', code: 'Code', invalidCanonical: 'Canonical must be a valid HTTP or HTTPS URL.', imageHint: 'Select only a ready public image; the largest variant is preferred.', selectFirst: 'Select content from the left column.',
  },
  zh: {
    eyebrow: '搜索优化', title: 'SEO 与社交分享', description: '按内容和语言管理元数据。', contentType: '内容类型', content: '内容', language: '语言', search: '搜索内容', refresh: '刷新', selectContent: '选择内容以编辑 SEO 元数据。', empty: '未找到内容。', loadError: '无法加载 SEO 数据。', saveError: '无法保存 SEO 元数据。', saved: 'SEO 元数据已保存。', save: '保存更改', searchResult: '搜索结果', socialPreview: '社交预览', basic: '搜索元数据', social: 'Open Graph 与 Twitter', advanced: '高级', metaTitle: 'SEO 标题', metaDescription: 'SEO 描述', canonical: '自定义 Canonical URL', canonicalHint: '留空则使用公开路由生成的 URL。', index: '内容发布后允许索引', follow: '允许爬虫跟踪链接', ogTitle: 'Open Graph 标题', ogDescription: 'Open Graph 描述', ogType: 'Open Graph 类型', twitterCard: 'Twitter 卡片', twitterTitle: 'Twitter 标题', twitterDescription: 'Twitter 描述', image: '分享图片', chooseImage: '选择图片', removeImage: '移除图片', focusKeywords: '重点关键词', focusHint: '用逗号分隔，仅供编辑，不会生成 meta keywords。', titleGuide: '建议 50–60 个字符', descriptionGuide: '建议 140–160 个字符', noTitle: '将使用后备标题', noDescription: '将使用后备描述', product: '产品', crop_solution: '作物解决方案', service: '服务', post: '文章', project: '项目', gallery: '图库', certification: '认证', vehicle: '车辆', transport_route: '运输路线', transport_service_area: '服务区域', warehouse: '仓库', website: '网站', article: '文章', summary: '摘要', summary_large_image: '带大图的摘要', vi: '越南语', en: 'English', zh: '中文', draftWarning: '草稿、预览和管理页面始终为 noindex。', loading: '加载中…', status: '状态', code: '代码', invalidCanonical: 'Canonical 必须是有效的 HTTP 或 HTTPS URL。', imageHint: '仅选择已就绪的公开图片；系统优先使用最大变体。', selectFirst: '请从左栏选择内容。',
  },
};
